# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.input = QtWidgets.QPushButton(Dialog)
        self.input.setGeometry(QtCore.QRect(240, 310, 93, 28))
        self.input.setObjectName("input")
        self.Reportes = QtWidgets.QPushButton(Dialog)
        self.Reportes.setGeometry(QtCore.QRect(400, 310, 93, 28))
        self.Reportes.setObjectName("Reportes")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 150, 251, 51))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.input.setText(_translate("Dialog", "Ver diarios"))
        self.Reportes.setText(_translate("Dialog", "Ver reportes"))
        self.label.setText(_translate("Dialog", "Bienvenidos al sistema contable del grupo 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
